### ISSUE TITLE
ImportError: cannot import name 'data_mnist'

### ISSUE THREAD

**Issue by TudouJack** [inspire-group/ModelPoisoning#10]
hello,Arjun.
When I ran the program according to README.md, there was an error that I cannot solve. 
Traceback (most recent call last):
  File "M:/Projects/Local model poison/ModelPoisoning/dist_train_w_attack.py", line 11, in <module>
    from utils.io_utils import data_setup, mal_data_setup
  File "M:\Projects\Local model poison\ModelPoisoning\utils\io_utils.py", line 9, in <module>
    from mnist import data_mnist
ImportError: cannot import name 'data_mnist'
Is the package mnist or python-mnist necessacy? How can I solve this error?

**Comment by TudouJack** [comment]
I ran the program with python3.6+tensorflow1.12.0

**Comment by TudouJack** [comment]
python2.7 and tf1.8 can solve it
